POST http://localhost:3333/users
Content-Type: application/json

{
  "userName": "Pedro1",
  "userDocument": "asedf111",
  "userEmail":"pedroh15101"
}
###
GET http://localhost:3333/users
Content-Type: application/json

{
  "userEmail":"pedroh15101"
}
