version: '3'
services:
  api:
    build: .
    container_name: criptografia
    entrypoint: ./.docker/entrypoint.sh
    working_dir: /usr/node/app
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./:/usr/node/app
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/mariadb:/var/lib/mysql
